### ISSUE TITLE
Error while running mapping_engine/main/main.go (Could not read mapping file "": open : no such file or directory)

### ISSUE THREAD

**Issue by pratikpagade1994** [GoogleCloudPlatform/healthcare-data-harmonization#10]
I'm getting the following error while running the main.go file with the required input parameters as defined in the README.md
I have following versions installed and added to the PATH.
Go        -  go1.15.3 darwin/amd64
Java     -  11.0.2
protoc -  3.13.0

 I have ran the build_all.sh file present in the root directory

 I have also ran the build.sh file present in the mapping_engine directorr

Screenshot of the error:
<img width="1438" alt="Screen Shot 2020-10-22 at 4 41 50 PM" src="https://user-images.githubusercontent.com/73318543/96940818-8e90eb00-1485-11eb-8f09-5f21cbdf3e20.png">

I'm i missing out something.

**Comment by yeweidaniel** [comment]
Hi, can you try removing the `--` and run again? Something like `go run . -input_file_spec=... -output_dir=... -mapping_file_spec=...`

**Comment by pratikpagade1994** [comment]
Great, thanks @yeweidaniel  its working now. Is '--' used to specify any flags ?( Since the README.md had it )

**Comment by yeweidaniel** [comment]
Great to hear. I don't think the `--` is used for anything, will send out a pull request to remove it from the README.

**Comment by pratikpagade1994** [comment]
yup, that would be helpful. thanks @yeweidaniel
