### ISSUE TITLE
JNI Wrapper

### ISSUE THREAD

**Issue by RokshanJ** [GoogleCloudPlatform/healthcare-data-harmonization#16]
@ygupta89 Hi , is there a JNI wrapper available for Whistle? If not any plan to publish that?

Thanks!

**Comment by yeweidaniel** [comment]
Hi, you can find a JNI wrapper in this repo: https://github.com/GoogleCloudPlatform/healthcare-data-harmonization-dataflow.

`build_deps.sh` builds the shared object and it is invoked here https://github.com/GoogleCloudPlatform/healthcare-data-harmonization-dataflow/blob/master/src/main/java/com/google/cloud/healthcare/etl/util/library/TransformWrapper.java#L48.

**Comment by RokshanJ** [comment]
Hi @yeweidaniel 

Thanks!. Does this wrapper support code & unit harmonization as well?

**Comment by yeweidaniel** [comment]
Yep both can be used via the wrapper.
