### ISSUE TITLE
Unable to run example notebook, possible permission issue with https://storage.googleapis.com/storage/v1/b/data-harmonization-sample-data

### ISSUE THREAD

**Issue by torstees** [GoogleCloudPlatform/healthcare-data-harmonization#32]
Very possibly user error, but my service account does have the Storage Admin role, yet I'm getting the following error: 

Forbidden: 403 GET https://storage.googleapis.com/storage/v1/b/data-harmonization-sample-data?fields=name: <service account email> does not have storage.buckets.get access to the Google Cloud Storage bucket.

I'm not sure how I can possibly grant my own service rights to some other group's bucket, but, I'm pretty green regarding cloud stuff and may have no idea what the underlying call really is trying to do.

**Comment by vneilley** [comment]
I believe your service account that you are running the notebook from does not have Google Cloud Storage access. Did you create a service account - as specified under the "running the image instructions" Under IAM tab within GCP you are able to grant access as "cloud storage admin" to the notebook service account? Also - where are you running the notebook? Vertex user-managed notebooks have a different set of permissions: https://cloud.google.com/vertex-ai/docs/workbench/user-managed/iam

**Comment by torstees** [comment]
So, when I'm inside console for the relevant project and select IAM and then edit the service account, I have two roles: Healthcare HL7v2 Message editor and Storage Admin. 

The notebook resides on my desktop running via WSL2 + Docker on windows. Maybe that's the problem?

**Comment by torstees** [comment]
I'm curious as to why that setup isn't working. I have used service accounts to interact with google's FHIR rest API just fine from my local dev machine via python. But, I don't need access to any of regular storage, though.

**Comment by torstees** [comment]
I'm not doing anything. I'm just hitting play on the notebook. The docker .env file does point to the json key file via the two vars and they are correctly configured.

**Comment by torstees** [comment]
I'm pretty sure I followed whatever directions were provided by the notebook repo closely, but I may have missed something. In the end, I just figured out whistle with out the notebook's functionality. Took a bit of digging into what sort of magic was going on in the background of some of the notebook example calls, but I learned what I needed. Closing the issue since it doesn't seem to be relevant to anyone.

**Comment by BusiPlay** [comment]
I am having the same issue - the bucket referenced in the instructions does not appear to be public, nor is it in my project:
curl -H "Authorization: Bearer $(gcloud auth print-access-token)" https://storage.googleapis.com/storage/v1/b/data-harmonization-sample-data?fields=name returns access forbidden whether I use my GCP credentials or my service account's

Is the data-harmonization-sample-data bucket restricted? How does one get access to this bucket?
